version: '3.8'

services:
  localdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: localdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - localdb:/var/lib/postgresql/data

volumes:
  localdb:
    driver: local
